name: "My composite action"
description: "Test Santander Path"

jobs:
  run-github-actions-using-checkout:
    runs-on: ubuntu-latest
    steps: 
     - name: Test Step 
       run: |
        echo "Hi Santander "