name: Actions WF

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: SImple JS Action
        id: idRun
        #@Codigo del commit || @master NO RECOMENDADO PORQUE CAMBIA
        uses: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
        # INPUTS DE LA DOCU
        with:
          who-to-greet: Carlos Neila
      - name : Log Time
        #Time OUPUT DE LA DOCU
        run: echo "${{steps.idRun.outputs.time}}"    
 
