name: Actions WF

on: [push]

jobs:
  run-github-actions-using-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: List Files CNEIL
        id: Pre-checkout
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"          
      - name: Checkout CNEILA
        id: Checkout
        #EXTERNAL ACTION https://github.com/actions/checkout
        uses: actions/checkout@v1
      - name: List Files CNEILA  AFTERCHECK
        id: Post-checkout
        run: |
          pwd
          ls -a
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      - name: Default ENV Variables
        id: getversion
        run: |
          pwd
          ls -a
          echo "HOME: ${HOME}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "::set-output name=version::$(cat config.yaml)"
          echo "Valuea $(cat ./config.yaml)"
          echo "Value 2 $(cat config.yaml)"     
      - name: Execute Action
        id: idRun
        #@Codigo del commit || @master NO RECOMENDADO PORQUE CAMBIA
        uses: cneila/santander-europe-read-yaml@main
        # INPUTS DE LA DOCU
        with:
          # INPUT NAME: "path"
          path: ${{ steps.getversion.outputs.version }}
          # https://api.github.com/repos/${{ github.repository }}/random.txt
      - name : Log Time
        #"time" del JS OUPUT DE LA DOCU
        run: echo "${{steps.idRun.outputs.time}}"    
 
