name: Shell Commands

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: voy a pintar un String
        run: echo "pull_request ANY BRANCH PRUEBA"
      - name: Ejecuto Varias Instrucciones
        run: |
          node -v
          npm -v
          echo ${{github.ref}}
      - name: Ejecuto En otro shell Instrucciones
        run: |
          (Get-Command java | Select-Object -ExpandProperty Version).toString()         
        shell: pwsh

name: Shell Commandsw

on: [issue_comment]

  jobs:
    pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
  
     