name: Shell Commands

on: 
  repository_dispatch:
    types:[build]
     
  push:
    branches:
      - master
      - 'feature/*'
    #branches-ignore:
      #- null
    tags:
      - v1.*
    
    paths-ignore:
      - '**.js'
      #!Excepto
    #*-ignore      
  
  #schedule:
    #- cron: "0/5 * * * *"
    #- cron: "0/6 * * * *"
    # minutes hours day of mohtn month day of week * cualquier día mes..
    # 1,2,3-6,0/10 * * * * https://crontab.guru/#1,2,3-6,0/10_*_*_*_*
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: voy a pintar un String
        run: echo "pull_request ANY BRANCH PRUEBA"
      - name: Ejecuto Varias Instrucciones
        run: |
          node -v
          npm -v
          echo ${{github.ref}}
      - name: Ejecuto En otro shell Instrucciones
        run: |
          (Get-Command java | Select-Object -ExpandProperty Version).toString()         
        shell: pwsh
  
     