name: Parse File YAML

on:
  workflow_dispatch:
    inputs:
      targetEnvironment:
        required: true
        description: Target environment
        type: choice
        options: 
          - DEV
          - PRE
          - PRO
      inputFileName:
        required: true
        description: File name
        type: string 
        default: 'config.yml' 

jobs:  
  get-json-from-yaml:
    runs-on: ubuntu-latest
    if:  ${{ inputs.inputFileName }} 
    steps:
      
      - uses: actions/checkout@v3
      - name: Default ENV Variables
        id: getversion
        run: |
          pwd
          ls -a
          echo "HOME: ${HOME}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "::set-output name=filaName::$(cat ${{ inputs.inputFileName }})"         
          echo "::set-output name=workspace::${HOME}"
      - name: Execute Action
        id: idRun
        #@Codigo del commit || @master NO RECOMENDADO PORQUE CAMBIA
        uses: cneila/santander-europe-read-yaml@main
        # INPUTS DE LA DOCU
        with:
          # INPUT NAME: "path"
          path: ${{ inputs.inputFileName }}
          workspace:  ${{steps.getversion.outputs.workspace}}       
      - name: Read File Action
        id: readfile
        run: |                   
          content=`cat ./output.json`         
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"          
          echo "::set-output name=packageJson::$content"
      - name: Get Properties JSON
        id: getproperties
        run: |             
          echo "${{ fromJson(steps.readfile.outputs.packageJson).service.type }}"           
      - name : Log Time
        #"time" del JS OUPUT DE LA DOCU
        run: echo "${{steps.idRun.outputs.time}}"    
