name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: voy a pintar un String
        run: echo "Mi String"
      - name: Ejecuto Varias Instrucciones
        run: |
          node -v
          npm -v
          echo ${{github.ref}}
      - name: Ejecuto En otro shell Instrucciones
        run: |
          (Get-Command java | Select-Object -ExpandProperty Version).toString()         
        shell: pwsh  
      